### ISSUE TITLE
Custom Fields in Jira

### ISSUE THREAD

**Issue by colePrato-zz** [CopadoSolutions/ccm-integration#2]
Need to know how bring over the value of a dropdown in JIRA as shown in the screenshot, able to bring over the value of another just custom field but not this. Thanks

<img width="777" alt="screen shot 2018-10-01 at 4 17 34 pm" src="https://user-images.githubusercontent.com/43420867/46313341-9bd49780-c595-11e8-94fb-eb96d55c5152.png">

**Comment by umitcanuckan** [comment]
Hi colePrato,

First of all, you need to create a record on Field mappings object under project between customfield_11316 and your salesforce field. By default, we map "name" field from object type field response however, you can add your own logic to map "value" response instead in JiraIntegration class.
