### ISSUE TITLE
Test Class Failure

### ISSUE THREAD

**Issue by robhosma** [CopadoSolutions/ccm-integration#6]
Hi

the class TestIntegration failes with the error:
System.AsyncException: Based on configured schedule, the given trigger 'SCHEDULED_APEX_JOB_TYPE.000000000000000' will never fire.
Stack Trace: Class.TestIntegration.testMethod2FetchfromJIRA: line 55, column 1

and

System.AsyncException: Based on configured schedule, the given trigger 'SCHEDULED_APEX_JOB_TYPE.000000000000000' will never fire.
Stack Trace: Class.TestIntegration.testMethod2FetchfromVSTS: line 71, column 1

Only during deployments when all local test are run but not when run individually in either source or target org.
We already tried an increase of the 5 seconds in line 54 and 70 but the test failed regardless.

Any help would be greatly appreciated ...

Thank you in advance
Robert

**Comment by tugce** [comment]
This is/was a Salesforce bug. We fixed it by increasing the time on the test class for scheduled class. I am closing this issue since it is resolved.
