### ISSUE TITLE
test class failure

### ISSUE THREAD

**Issue by mani2246** [CopadoSolutions/ccm-integration#7]
All 4 methods in the test class fail with this error:

ERROR | Test   failure, method: TestIntegration.testMethod2FetchfromJIRA --   System.LimitException: Too many query rows: 50001 stack   Class.Database.QueryLocatorIterator.hasNext: line 41, column 1   Class.CopadoCCMutilities: line 88, column 1 Class.JiraIntegration.fetchRecords:   line 153, column 1 Class.ExecuteUserStoryUpsert.start: line 31, column 1
-- | --
ERROR | Test   failure, method: TestIntegration.testMethod2FetchfromVSTS --   System.LimitException: Too many query rows: 50001 stack   Class.Database.QueryLocatorIterator.hasNext: line 41, column 1   Class.CopadoCCMutilities: line 88, column 1 Class.VSTSIntegration.fetchRecords:   line 116, column 1 Class.ExecuteUserStoryUpsert.start: line 31, column 1
ERROR | Test   failure, method: TestIntegration.testMethod2UpdateJIRA --   System.LimitException: Too many query rows: 50001 stack   Class.Database.QueryLocatorIterator.hasNext: line 41, column 1   Class.CopadoCCMutilities: line 88, column 1   Class.JiraIntegration.__sfdc_fieldMap: line 66, column 1   Class.JiraIntegration.__sfdc_queryFields: line 89, column 1   Class.JiraIntegration.updateRecord: line 107, column 1 Class.UserStoryHandler.callFactory4ThirdPartyUpdate:   line 27, column 1
ERROR | Test   failure, method: TestIntegration.testMethod2UpdateVSTS --   System.LimitException: Too many query rows: 50001 stack   Class.Database.QueryLocatorIterator.hasNext: line 41, column 1   Class.CopadoCCMutilities: line 88, column 1   Class.VSTSIntegration.__sfdc_fieldMap: line 73, column 1   Class.VSTSIntegration.__sfdc_queryFields: line 81, column 1   Class.VSTSIntegration.updateRecord: line 94, column 1   Class.UserStoryHandler.callFactory4ThirdPartyUpdate: line 27, column 1

**Comment by tugce** [comment]
Hi @mani2246 
It appears in your organization there are more than 50k active users. This can be generally caused by communities. You need to put Limit and add extra conditions to the query like Profile, UserType = 'Standard' etc to reduce the number of users returned by that query.

Here is the line that is causing this error in your case:
https://github.com/CopadoSolutions/ccm-integration/blob/e37a5866f2065c7f6c31d3d948876b919e10f52b/classes/CopadoCCMutilities.cls#L88

**Comment by mani2246** [comment]
> Hi @mani2246
> It appears in your organization there are more than 50k active users. This can be generally caused by communities. You need to put Limit and add extra conditions to the query like Profile, UserType = 'Standard' etc to reduce the number of users returned by that query.
> 
> Here is the line that is causing this error in your case:
> https://github.com/CopadoSolutions/ccm-integration/blob/e37a5866f2065c7f6c31d3d948876b919e10f52b/classes/CopadoCCMutilities.cls#L88

Thanks @tugce that was the cause. Wouldn't it be better to setup test user in the test setup method instead of querying the org for all users.

**Comment by tugce** [comment]
While that is true, it is best practice to setup test user for the unit test, if you don't change the query the actual integration will also fail. So test class is a good indicator that you need to update the query to fit your environment.

**Comment by mani2246** [comment]
Thanks. Please update the readme providing these details.
