### ISSUE TITLE
Unable to sync stories in Azure DevOps (Earlier known as VSTS)

### ISSUE THREAD

**Issue by abhisheksaxena7** [CopadoSolutions/ccm-integration#9]
When using the default field mapping that's provided in this repository, we kept running into the error "Attempt to de-reference a null object"

This should not be the expected behavior.

**Comment by umitcanuckan** [comment]
Hi Abhishek,

Can you please confirm that you were working with our unlocked package and adding copadoccmint to package fields on the field mapping solved your issue?

Best,

**Comment by abhisheksaxena7** [comment]
Hey @umitcanuckan  - Yes I am working with the CCM unlocked package and adding the package namespace to the fields resolved this issue.
